"""Added Created By in Folders

Revision ID: 511b162b6c65
Revises: e35799437518
Create Date: 2024-06-24 11:41:12.923171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511b162b6c65'
down_revision = 'e35799437518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
